### ISSUE TITLE
Найденные сложности при прохождении кодлабы №1

### ISSUE THREAD

**Issue by AnthonyNSK** [icerockdev/kmp-codelabs#37]
1. Скрины и пути указаны для старой Android Studio, Google убрала часть настроек в други е места. Установлена Arctic Fox 2020.3.1
2. В новой версии студии отсутствует возможность конфигурирования из стартового окна. Теперь это делается в Android Studio -> Preferences
3. Не удалось установить Kotlin Multiplatform Mobile plugin (iOS)
4. Необходимо зафиксировать, что при указании путей в Android Studio нельзя использовать ~ (тильда). С ней путь определяется некорректно и сборка фейлится.
5. Создал issue для moko-doctor - предлагаю правки скрипта
6. Проблемы раздела Gradle Build Environment - для человека, который первый раз это открывает не совсем очевидно какие значения лучше всего поставить для его конкретной машинки.

Возможно появятся новые пункты по мере прохождения лабы

- [x] заменить скрины старой Android Studio
- [x] Указать как делать конфигурации в новой Android Studio
- [x] указать что в Android Studio нельзя использовать ~ в пути (!)
- [x] написать про настройку Gradle build environment для конкретной машины
- [x] добавить про альтернативный способ установки KMM plugin'а для Android Studio - через Pref's -> Plugins

**Comment by kramlex** [comment]
- [ ] заменить скрины старой Android Studio
- [ ] Указать как делать конфигурации в новой Android Studio
- [ ] указать что в Android Studio нельзя использовать ~ в пути (!)
- [ ] написать про настройку Gradle build environment для конкретной машины
